### ISSUE TITLE
Is there a way to use system Ruff?

### ISSUE THREAD

**Issue by FCamborda** [astral-sh/ruff-pre-commit#105]
Hi,

currently we setup our pre-commit specifying a revision for Ruff.
```yaml
repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.8.0
  hooks:
    # Run the linter.
    - id: ruff
    # Run the formatter.
    - id: ruff-format
```

This installs Ruff with version 0.8.0 and works very well. However, every time we upgrade our dependencies, we have to maintain different places where the Ruff version is defined.
We would like for pre-commit to use Ruff as-is found via PATH (either installed via Shell, or if installed in an isolated venv like with `uv tool install`).
