### ISSUE TITLE
Add instructions in README for how to select ruff linter rules or ignore others

### ISSUE THREAD

**Issue by jgarte** [astral-sh/ruff-pre-commit#107]
Hi,

This is a feature request for the README on adding explicit instructions on how to select ruff linter rules or ignore rules, etc.

**Comment by MichaReiser** [comment]
You're doing it right, but you need to specify the command you want to run. For example see

https://github.com/rio-labs/rio/blob/01472d6854739fa387812e0f3a9107c9bdcfb2e4/.pre-commit-config.yaml#L2

**Comment by MichaReiser** [comment]
Can you tell me more about why this is invalid, I'm trying to understand the issue you're facing

**Comment by jgarte** [comment]
Hi, IIRC It was a ConfigError or similar. I'll reproduce soon again and get back to you with the exact stack trace, if needed. On my phone at the moment.

**Comment by bethdehart** [comment]
I have run into this as well.

```yml
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.2
    hooks:
      - id: ruff-check
        args: [ --extend-select I,E, --fix ]
```

```bash
ruff check...............................................................Failed
- hook id: ruff-check
- duration: 0.02s
- exit code: 2

error: unexpected argument '--extend-select I,E' found

  tip: a similar argument exists: '--extend-select'

Usage: ruff check --force-exclude --extend-select <RULE_CODE> [FILES]...

For more information, try '--help'.
```

So I converted it to a local hook for testing
```yml
repos:
  -   repo: local
      hooks:
        - id: ruff-check
          name: ruff check
          description: "Run 'ruff check' for extremely fast Python linting"
          entry: ruff check --force-exclude
          language: python
          types_or: [python, pyi, jupyter]
          require_serial: true
          args:
            - --extend-select I,E
```

Same error... then I tried to print what is going on.

```yml
repo:
  -   repo: local
      hooks:
        - id: ruff-check
          name: ruff check
          description: "Run 'ruff check' for extremely fast Python linting"
          entry: echo "ruff check --force-exclude"
          language: python
          types_or: [python, pyi, jupyter]
          require_serial: true
          verbose: true # <-- Super helpful
          args:
            - --extend-select I,E
```

Output:
```bash
> pre-commit run -a
ruff check...............................................................Passed
- hook id: ruff-check
- duration: 0.01s

ruff check --force-exclude --extend-select I,E build.py
```

So I see the command with the args looks fine and it found the files I want to check. Let me run this from my shell
```bash
ruff check --force-exclude --extend-select I,E build.py
```

Output:
```bash
> ruff check --force-exclude --extend-select I,E build.py
All checks passed!
``` 

Once I remove the "echo" and quotes.

```yml
repo:
  -   repo: local
      hooks:
        - id: ruff-check
          name: ruff check
          description: "Run 'ruff check' for extremely fast Python linting"
          entry: ruff check --force-exclude
          language: python
          types_or: [python, pyi, jupyter]
          require_serial: true
          verbose: true
          args:
            - --extend-select I,E
```

```shell
> pre-commit run -a
ruff check...............................................................Failed
- hook id: ruff-check
- duration: 0.02s
- exit code: 2

error: unexpected argument '--extend-select I,E' found

  tip: a similar argument exists: '--extend-select'

Usage: ruff check --force-exclude --extend-select <RULE_CODE> [FILES]...

For more information, try '--help'.
```

Ideas?
