### ISSUE TITLE
Local pre-commit different than CI pre-commit

### ISSUE THREAD

**Issue by uditrana** [astral-sh/ruff-pre-commit#121]
# Inconsistent Ruff Import Formatting Between Local and CI Environments

## Issue Description

We're encountering a persistent issue where Ruff behaves inconsistently between local and CI environments when formatting imports. Specifically:

1. **Local Environment**: Ruff insists on **adding blank lines** between different third-party import blocks
2. **CI Environment**: Ruff insists on **removing** at leat one of these same blank lines

This creates an impossible situation where:
- Locally, pre-commit adds blank lines
- We push the changes
- CI fails because it wants to remove those lines
- If we remove the lines locally to match CI, then local pre-commit fails

The issue seems to occur most frequently with imports involving `wandb` packages.

### Example File Imports
```python
import datetime
import logging
from pathlib import Path
from typing import TYPE_CHECKING
from lightning.pytorch import Trainer
from lightning.pytorch.loggers import WandbLogger
from wandb import Api as wandb_Api
from wandb.apis.public.runs import Run as wandb_Run
```

### Local Pre-commit Output
When running locally **without** the blank line between Lightning and WandB imports:

```console
❯ uv run pre-commit run --from-ref origin/main --to-ref HEAD --show-diff-on-failure
# ... [other checks pass] ...
ruff.....................................................................Failed
- hook id: ruff
- files were modified by this hook

Found 1 error (1 fixed, 0 remaining).
# ... [other checks pass] ...

All changes made by hooks:
diff --git a/src/path/to/file.py b/src/path/to/file.py
index 1d31175..f6a75e6 100644
--- a/src/path/to/file.py
+++ b/src/path/to/file.py
@@ -2,8 +2,10 @@ import datetime
 import logging
 from pathlib import Path
 from typing import TYPE_CHECKING
+
 from lightning.pytorch import Trainer
 from lightning.pytorch.loggers import WandbLogger
+
 from wandb import Api as wandb_Api
 from wandb.apis.public.runs import Run as wandb_Run
```

Local Ruff **adds** the blank lines between import groups.

### CI Output
When the exact same file (including the blank lines) is processed in CI:

```console
ruff.....................................................................Failed
- hook id: ruff
- files were modified by this hook

Found 1 error (1 fixed, 0 remaining).
# ... [other checks pass] ...

All changes made by hooks:
diff --git a/src/path/to/file.py b/src/path/to/file.py
index f6a75e6..caa7737 100644
--- a/src/path/to/file.py
+++ b/src/path/to/file.py
@@ -5,7 +5,6 @@ from typing import TYPE_CHECKING
 
 from lightning.pytorch import Trainer
 from lightning.pytorch.loggers import WandbLogger
-
 from wandb import Api as wandb_Api
 from wandb.apis.public.runs import Run as wandb_Run
```

CI Ruff **removes** the blank line between the imports. But notably, it seems to **only** remove the the blank line before the `wandb` import, not the one before `lightning`.

### `.pre-commit-config.yaml`
```yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-ast
      - id: check-yaml
      - id: check-toml
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: check-case-conflict
      - id: check-docstring-first
      - id: debug-statements
      - id: forbid-new-submodules

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.6.11
    hooks:
      - id: uv-lock
      - id: uv-sync
        args: ["--locked"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.2
    hooks:
      - id: ruff
        args: [--config=pyproject.toml, --fix]
      - id: ruff-format
        args: [--config=pyproject.toml]

  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.1
    hooks:
      - id: nbstripout

  - repo: https://github.com/hukkin/mdformat
    rev: 0.7.22
    hooks:
      - id: mdformat
        args: [--number]
        exclude: ^\.github/

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
```

### `pyproject.toml` (relevant sections)
```toml
[project]
requires-python = ">=3.13"
dependencies = [
    "lightning>=2.4.0",
    "wandb>=0.18.3",
]


[tool.uv]
dev-dependencies = [
    "pip>=24.2",
    "pre-commit>=4.0.1",
    "ruff==0.11.2",
]
[tool.ruff]
preview = true
line-length = 120
indent-width = 4
builtins = ["display", "dbutils"]
exclude = ["src/demos/"]

[tool.ruff.format]
preview = true

[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
    # type annotations
    "ANN",
    # NumPy-specific rules
    "NPY",
    # pandas rules
    "PD",
    # Builtins Protection
    "A",
    # Comprension improvements
    "C4",
]
ignore = ["W191", "E111", "E266", "E114", "E117", "E741", "E722", "PD901"]
pycodestyle = {max-line-length = 120}

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]
```

### GitHub Actions Workflow (`python-ci.yml`)
```yaml
name: Python DevOps CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        version: "0.6.11"
        enable-cache: true

    - name: Set up Python
      run: uv python install

    - name: Install dependencies
      run: |
        uv sync --all-extras --dev

    - name: Run pre-commit checks
      if: github.event_name == 'pull_request'
      run: |
        # Only run pre-commit in PR context
        echo "Running pre-commit on changed files between ${{ github.base_ref }} and current branch"
        git fetch origin ${{ github.base_ref }}
        uv run pre-commit run --from-ref origin/${{ github.base_ref }} --to-ref HEAD --show-diff-on-failure
```

## Attempted Solutions

We've tried several approaches without success:

1. Adding explicit isort configuration in `pyproject.toml`:
   ```toml
   [tool.ruff.lint.isort]
   lines-between-types = 0
   force-single-line = false
   lines-after-imports = 1
   section-order = ["future", "standard-library", "third-party", "first-party", "local-folder"]
   known-third-party = ["lightning", "wandb", "torch", "numpy", "pandas", "polars", "tensordict"]
   ```

2. Tinkering with the ordering of format, lint, fix, no-fix, etc. in the pre-commit config.

## Environment Information

- Ruff version: 0.11.2 (pinned in uv)
- Python version: 3.13.1
- Using uv 0.6.11 in both environments
- Local OS: Linux
- CI: GitHub Actions (ubuntu-latest)

We would greatly appreciate any guidance on resolving this inconsistency or understanding why Ruff behaves differently in these environments.
