### ISSUE TITLE
Fail to install pre-commit using ruff-check hook 

### ISSUE THREAD

**Issue by chiptuned** [astral-sh/ruff-pre-commit#126]
Just got the error 

```
[ERROR] `ruff-check` is not present in repository https://github.com/astral-sh/ruff-pre-commit.  Typo? Perhaps it is introduced in a newer version?  Often `pre-commit autoupdate` fixes this.
```

`.pre-commit-config.yaml` used from the readme :
```
repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.11.9
  hooks:
    # Run the linter.
    - id: ruff-check
    # Run the formatter.
    - id: ruff-format
```

Starting from a clean state. To reproduce : 
```
uv init 
touch .pre-commit-config.yaml 
<copied the config from the Readme example>
uv add pre-commit
uv run pre-commit install
git commit
```
I think commit 39f54b73c72a16ee873859353d1ef40552a22e4d affected that behavior in a way I haven't solved yet. 
However`ruff` hook still works.
