### ISSUE TITLE
How to configure include for pre-commit 

### ISSUE THREAD

**Issue by raianul** [astral-sh/ruff-pre-commit#71]
When I use `ruff` with `include` from my shell, its work and ignore all directory and only apply ruff to the include directory.

```
 ruff check --config 'include = ["core/others/"]'
```

But when I'm going to use `include` with `pre-commit` its not working 

```
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: 'v0.2.2'
    hooks:
      - id: ruff
        include: "[core/drones/api_extern/**/*.py]"
```

But `exclude` works - 

```
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: 'v0.2.2'
    hooks:
      - id: ruff
        exclude: "(core/others/)"
```

I'm using a `ruff.toml` also where `exclude=[...]` basing excluding list.
