### ISSUE TITLE
--check option for ruff-format

### ISSUE THREAD

**Issue by 57an** [astral-sh/ruff-pre-commit#73]
Such option is available in ruff format, but inside precommit config gives no effect.

```
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.0
    hooks:
      - id: ruff-format
    args: ['--check']
``` 
now results as reformatting instead of just checking

Possibly it is a repeat of https://github.com/astral-sh/ruff-pre-commit/issues/61, but in black there is ability to just check without formating

**Comment by edgarrmondragon** [comment]
You might have the wrong indentation:

```yaml
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.0
    hooks:
      - id: ruff-format
        args: ['--check'] # <- here!
```
