### ISSUE TITLE
How to limit checks to certain directories?

### ISSUE THREAD

**Issue by hakonhagland** [astral-sh/ruff-pre-commit#75]
How to limit checks to certain directories?

I tried:

```
-   repo: https://github.com/astral-sh/ruff-pre-commit.git
    rev: v0.3.3
    hooks:
      - id: ruff
        args: [ "--fix", "src", "tests" ]
      - id: ruff-format

```
but it still checks files in my `docs` folder. So apparently it is not restricted to `src` and `tests` as expected.
