### ISSUE TITLE
Run on pyproject.toml or ruff.toml change

### ISSUE THREAD

**Issue by almahdi404** [astral-sh/ruff-pre-commit#79]
Currently ruff runs on `py` or `pyi` file change.

But shouldn't it also run when `pyproject.toml` or `ruff.toml` is changed?

**Comment by CoderJoshDK** [comment]
The problem is that `pre-commit` will only run on the file changed. There is not a way to check for a config change and then run ruff on all files (not without making this whole system wildly more complicated.) You can manually have it ran on `all-files` when you make changes. Otherwise, you would need `always_run`. But that would be excessive most of the time. 

When you make a change to your config, you can run:

```sh
> pre-commit run ruff --all-files # `ruff` is the `id` of the pre-commit hook you are referencing
ruff.....................................................................Passed

> pre-commit run ruff-format --all-files
ruff-format..............................................................Passed
```

**Comment by charliermarsh** [comment]
We do lint the `pyproject.toml` itself though, so we _could_ add `toml` to the list of supported files. We did this in the past and then had to revert it: https://github.com/astral-sh/ruff-pre-commit/pull/44#issuecomment-1629510474. But I believe newer versions of Ruff don't suffer from the same problem, so we could re-add.

**Comment by almahdi404** [comment]
pre-commit passes changed files as arguments to the `entry`.

What if ruff cli runs on the whole project if the arguments include `pyproject.toml` or `ruff.toml`

**Comment by CoderJoshDK** [comment]
That could work. You should [open an issue in `ruff`](https://github.com/astral-sh/ruff/issues/new). It would solve this issue. But I have no idea if it would be approved.

**Comment by BHSPitMonkey** [comment]
Couldn't there simply be two additional hook definitions, e.g. `ruff-check-everything` and `ruff-format-everything`, which set `pass_filenames: false` and match on `files: (pyproject|ruff)\.toml$` (with `types: [file]`)?

**Comment by GideonBear** [comment]
I solved it with:
```yaml
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.21
    hooks:
      - id: ruff-check
      - id: ruff-check
        alias: ruff-check-pyproject
        name: ruff check (pyproject.toml)
        types_or: [toml]
        files: pyproject\.toml$
```
This does not rerun ruff on all files when `pyproject.toml` is modified; I use `pre-commit --all-files` in CI for that. But this does correctly run ruff on `pyproject.toml` without also running on `uv.lock`.
