### ISSUE TITLE
Can ruff-pre-commit be configured to replace pre-commit-hooks like trailing-whitespace, end-of-file-fixer and check-ast?

### ISSUE THREAD

**Issue by mcarans** [astral-sh/ruff-pre-commit#80]
I am using some pre-commit-hooks along with ruff. Can ruff already do what those pre-commit hooks (trailing-whitespace, end-of-file-fixer and check-ast) do? If so, how do I configure the ruff pre-commit to replace any or all of those hooks? 
  
```
- repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-ast
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.2
    hooks:
      # Run the linter.
      - id: ruff
        args: [--config, .config/ruff.toml, --fix]
      # Run the formatter.
      - id: ruff-format
        args: [--config, .config/ruff.toml]
```
