### ISSUE TITLE
--range support

### ISSUE THREAD

**Issue by skairunner** [astral-sh/ruff-pre-commit#94]
Ruff introduced a new parameter `--range` that allows the formatter to only check the specified range. This would be useful to allow migrating from black to ruff formatting without causing whole-file diffs whenever a file is touched for the first time. 

Is there a way to have range support within the pre-commit framework?

**Comment by AlexWaygood** [comment]
Hi! Would you be able to do this using the `args` key in your `.pre-commit-config.yaml` file? E.g. something like

```yaml
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.7
    hooks:
      - id: ruff
        name: Run ruff on stubs, tests and scripts
        args: ["--range=1:2-3:4"]
```
